[project]
name = "udemy-agentic-ai-krishnaik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "langchain>=0.3.27",
    "langgraph>=0.5.4",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
]
